issuer: https://token.actions.githubusercontent.com
subject: repo:xnox/rules_apko:ref:refs/heads/main
claim_pattern:
  job_workflow_ref: xnox/rules_apko/.github/workflows/release.yaml@refs/heads/main

permissions:
  contents: write
  pull_requests: write
  workflows: write
  
